-- Cinderblock — Migration 0010
-- cb_audit_writer + cb_impersonator roles.
--
-- Both roles use the session-mode Postgres port (:5432) from the Next.js
-- server, not the transaction pooler at :6543. supabase-js cannot express the
-- transaction control these roles need (`set local request.jwt.claims`,
-- serializable isolation for seat enforcement), so direct connections via
-- postgres-js are the right tool.
--
-- Passwords are generated by scripts/postclone.sh on first setup and written
-- to PG_AUDIT_WRITER_URL / PG_IMPERSONATOR_URL in the local .env.
--
-- cb_audit_writer has INSERT-only grants on audit_events (created in a later
-- migration; the grant runs there once the table exists). No SELECT on any
-- public-schema table. The role exists to make "the Next.js app cannot
-- UPDATE or DELETE an audit row" a property of the database, not of
-- application code that could be circumvented by a future regression.
--
-- cb_impersonator has the same baseline grants as `authenticated` and
-- NOBYPASSRLS. With `set local request.jwt.claims` setting the target user's
-- sub claim, every read/write evaluates as the impersonated user — admins
-- cannot accidentally do something the impersonated user couldn't.

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'cb_audit_writer') then
    create role cb_audit_writer noinherit nologin;
    comment on role cb_audit_writer is
      'Cinderblock: INSERT-only on public.audit_events. Connected to by Next.js for direct audit writes. Password set by scripts/postclone.sh; rotation flow lives in /docs/security/role-rotation.';
  end if;

  -- Re-grant `login` once postclone.sh sets the password; the migration leaves
  -- the role NOLOGIN so an unconfigured fork can't accidentally authenticate.
end;
$$;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'cb_impersonator') then
    create role cb_impersonator noinherit nologin nobypassrls;
    -- Inherit the same grant set as `authenticated`. Supabase's `authenticated`
    -- role is created with usage on the public schema + select on tables added
    -- to the data API; granting `authenticated` to cb_impersonator copies those
    -- grants forward without re-listing every table.
    grant authenticated to cb_impersonator;
    comment on role cb_impersonator is
      'Cinderblock: same grants as authenticated, NOBYPASSRLS. Used during active impersonation sessions with set local request.jwt.claims setting sub=<target>. Password set by scripts/postclone.sh.';
  end if;
end;
$$;

-- Tightening: revoke direct access to extensions that the data API never needs
-- from either role. This is defense-in-depth — the public default doesn't
-- normally expose these, but explicit revokes mean a future Postgres major
-- version that flips a default can't silently widen access.
revoke all on schema pg_catalog from cb_audit_writer, cb_impersonator;
grant usage on schema pg_catalog to cb_audit_writer, cb_impersonator;

-- Both roles need usage on the public schema for the grants on tables to
-- mean anything. The actual table-level grants happen in the migrations that
-- create those tables (e.g. audit_events grants INSERT to cb_audit_writer
-- in that migration).
grant usage on schema public to cb_audit_writer, cb_impersonator;
